name: torch
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiodns=3.5.0=py39h06a4308_0
  - aiohappyeyeballs=2.6.1=py39h06a4308_0
  - aiohttp=3.12.15=py39hb25bd0a_0
  - aiosignal=1.4.0=py39h06a4308_0
  - aom=3.6.1=h59595ed_0
  - arrow-cpp=19.0.0=h865e1df_1
  - async-timeout=5.0.1=py39h06a4308_0
  - attrs=25.4.0=py39h06a4308_1
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.11.212=hecad206_0
  - blas=1.0=mkl
  - brotli=1.0.9=h5eee18b_9
  - brotli-bin=1.0.9=h5eee18b_9
  - brotli-python=1.0.9=py39h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.18.0=hbb29018_2
  - certifi=2025.10.5=py39h06a4308_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h74842e3_2
  - cpython=3.9.23=py39hd8ed1ab_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cudatoolkit=11.8.0=h6a678d5_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=h1110e0f_3
  - datasets=3.3.2=py39h06a4308_0
  - dbus=1.16.2=h5bd4931_0
  - dill=0.3.8=py39h06a4308_0
  - eigen=3.4.0=h171cf75_1
  - expat=2.7.3=h3385a95_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.19.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h2c49b7f_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.59.1=py39heb7d2ae_0
  - freetype=2.14.1=ha770c72_0
  - frozenlist=1.8.0=py39hbdd6827_0
  - fsspec=2024.12.0=py39h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.2=h5eee18b_0
  - glib=2.84.0=h07242d1_0
  - glib-tools=2.84.0=h4833e2c_0
  - glog=0.5.0=h6a678d5_1
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py39h7196dd7_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.14=hecca717_2
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=4.3.0=hf52aaf7_2
  - hdf5=1.12.1=h2b7332f_3
  - hf-xet=1.1.8=py39h84c0859_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - huggingface_hub=0.34.4=py39h06a4308_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jinja2=3.1.6=py39h06a4308_0
  - jpeg=9e=h166bdaf_2
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240116.2=cxx17_he02047a_1
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcblas=3.9.0=12_h832b8c9_netlib
  - libclang=14.0.6=default_h7634d5b_1
  - libclang13=14.0.6=default_h9986a30_1
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcups=2.3.3=h36d4200_3
  - libcurand=10.3.5.147=0
  - libcurl=8.16.0=heebcbe5_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.0=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h4751f2c_7
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hfac485b_1
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=12_hd37a5e2_netlib
  - libllvm14=14.0.6=hcd5def8_4
  - libnghttp2=1.67.0=had1ee68_0
  - libnpp=11.8.0.86=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjpeg=11.9.0.86=0
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.6=ha51bf15_0
  - libprotobuf=4.25.3=hd5b35b9_1
  - libsodium=1.0.20=h4ab18f5_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtasn1=4.20.0=hb03c661_1
  - libthrift=0.15.0=hd8eb582_4
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libva=2.22.0=h4f16b4b_2
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=hd590300_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lmdb=0.9.31=hd590300_1
  - lz4-c=1.9.4=hcb278e6_0
  - markupsafe=3.0.2=py39h5eee18b_0
  - matplotlib-base=3.9.4=py39h16632d1_0
  - mkl=2023.1.0=h213fc3f_46344
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.7.0=py39hee96239_0
  - multiprocess=0.70.15=py39h06a4308_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql=8.4.0=h29a9f33_1
  - ncurses=6.5=h7934f7d_0
  - nettle=3.6=he412f7d_0
  - networkx=3.2.1=py39h06a4308_0
  - numpy=1.26.4=py39h474f0d3_0
  - opencv=4.10.0=py39h0a8ef67_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openldap=2.6.10=he9288cc_1
  - openssl=3.6.0=h26f9b46_0
  - orc=2.0.1=h2d29ad5_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py39h1b6b32d_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=hc749103_2
  - pillow=11.0.0=py39hfdbf927_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h54a6638_1
  - propcache=0.3.1=py39h5eee18b_0
  - psutil=7.0.0=py39h8cd3c5a_0
  - pthread-stubs=0.3=h0ce48e5_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pyarrow=19.0.0=py39h7934f7d_2
  - pycares=4.10.0=py39ha137689_0
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.3=pyhe01879c_2
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.25=h0dcde21_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.5.0=py39h5eee18b_0
  - python_abi=3.9=2_cp39
  - pytorch=2.5.1=py3.9_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py39h9399b63_2
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.2=hb6262e9_12
  - re2=2022.04.01=h295c915_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhd8ed1ab_0
  - s2n=1.3.27=hdbd6064_0
  - scipy=1.13.1=py39haf93ffa_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=py39h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.51.0=h2a70700_0
  - statsmodels=0.14.5=py39h7c0b2d6_0
  - svt-av1=1.4.1=hcb278e6_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=2.5.1=py39_cu118
  - torchtriton=3.1.0=py39
  - torchvision=0.20.1=py39_cu118
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=py39h06a4308_0
  - typing_extensions=4.15.0=py39h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - ultralytics=8.3.181=pyh2a12c56_0
  - unicodedata2=16.0.0=py39h8cd3c5a_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - utf8proc=2.6.1=h5eee18b_1
  - uvloop=0.22.1=py39h939ff40_0
  - wayland=1.24.0=hdac8c69_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wheel=0.45.1=py39h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - x265=3.5=h924138e_3
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - yarl=1.18.0=py39h5eee18b_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.23.0=py39hd399759_3
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - sympy==1.13.1
